# Generated by Django 3.2.9 on 2021-11-12 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('acc_num', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('balance', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_num', models.AutoField(primary_key=True, serialize=False)),
                ('pin', models.IntegerField(max_length=10)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('card_status', models.CharField(max_length=10)),
                ('account_num', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.account')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_balance', models.FloatField()),
                ('location', models.TextField()),
                ('minimum_balance', models.FloatField()),
                ('last_refill', models.DateTimeField()),
                ('next_maintenance_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('Transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('card_num', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.card')),
                ('machine_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.machine')),
            ],
        ),
    ]
