# Generated by Django 3.2.9 on 2021-11-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_account_card_machine_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acc_num',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_num',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
